
version: 2

models:

  - name: stg_nbaapi__player_shots
    description: >
      Staging model for player shot data from the NBA API ShotChartDetail endpoint.
      Cleans and standardises the raw shot-level data loaded from the raw schema - one row per nba shot attempt.

    columns:
      - name: player_id_nk
        description: Id of the player that took the shot, returned by nba_api.
        data_tests:
          - not_null


      - name: player_name
        description: Name of the player that took the shot, returned by nba_api.
        data_tests:
          - not_null
      
      - name: team_id
        description: NBA team identifier
        data_tests:
          - not_null

      - name: team_name
        description: NBA team name (full name)
        data_tests:
          - not_null

      - name: game_id_nk
        description: Natural key identifying the NBA game
        data_tests:
          - not_null

      - name: htm
        description: 3 letter abbreviation of the home team
        data_tests:
          - not_null

      - name: vtm
        description: 3 letter abbreviation of the visiting team
        data_tests:
          - not_null

      - name: game_date
        description: Date on which the game was played
        data_tests:
          - not_null

      - name: season
        description: Season in which the game was played
        data_tests:
          - not_null

      - name: shot_id_nk
        description: >
          Natural key for a shot attempt, created by combining game_id and game_event_id
        data_tests:
          - not_null
          - unique

      - name: game_event_id_nk
        description: The natural key from nba_api for the unique game event in a game
        data_tests:
          - not_null

      - name: event_type
        description: Indicates either 'missed shot' or 'made shot'
        data_tests:
          - not_null

      - name: action_type
        description: Type of basketball action implemented to take the shot
        data_tests:
          - not_null

      - name: shot_type
        description: Indicates 2pt or 3pt attempt
        data_tests:
          - not_null

      - name: shot_zone_basic
        description: >
          Shot is assigned to a specific shot zone on a basketball court
          Restricted area
          Above the break 3
          Mid-range
          In The Paint (Non-RA)
        data_tests:
          - not_null

      - name: shot_zone_area
        description: Indicates area on the court where shot was taken with a combination of [left, right, center]
        data_tests:
          - not_null

      - name: shot_zone_range
        description: Gives a rough range where shot was taken from (feet)
        data_tests:
          - not_null

      - name: shot_distance
        description: Exact shot distance (feet) from the basket
        data_tests:
          - not_null

      - name: loc_x
        description: Exact x-axis on the court where shot was taken from
        data_tests:
          - not_null

      - name: loc_y
        description: Exact y-axis on the court where shot was taken from
        data_tests:
          - not_null

      - name: is_bucket
        description: Indicates whether the shot was made or not with a 0 or 1
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]
                quote: false #Ensures it will NOT single-quote the list of accepted values
      
      - name: period_no
        description: Period of the game that the shot was taken in
        data_tests:
          - not_null
      
      - name: min_left
        description: Minutes left in the quarter when the shot was taken
        data_tests:
          - not_null

      - name: sec_left
        description: Seconds (+ minute) left in the quarter when the shot was taken
        data_tests:
          - not_null


  - name: stg_nbaapi__play_by_play
    description: >
      Staging model for shot events from the NBA API PlayByPlayV3 endpoint.
      Filters the raw play-by-play feed to field goal attempts only and standardises 
      the relevant shot-level fields

    columns:
      - name: player_id_nk
        description: Id of the player that took the shot, returned by nba_api.
        data_tests:
          - not_null

      - name: shot_id_nk
        description: >
          Natural id of the shot taken, derived from 'actionNumber' in nba_api. 
          Combination of game_id and game_event_id
        data_tests:
          - not_null
          - unique

      - name: game_id_nk
        description: Natural key identifying the NBA game
        data_tests:
        - not_null

      - name: home_pts
        description: Amount of points accumulated by the home team at the time of that game_event_id

      - name: away_pts
        description: Amount of points accumulated by the away team at the time of that game_event_id


  - name: stg_nbaapi__player_game
    description: >
      Staging model for individual player game statistics.
      One row per player per game.

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id_nk
              - game_id_nk

    columns:
      - name: player_id_nk
        description: Id of the player that played the game.
        data_tests:
          - not_null

      - name: game_id_nk
        description: Game in which the player played in
        data_tests:
          - not_null
      
      - name: season_id_nk
        description: Id of the season returned by nba_api
      
      - name: season
        description: Season in which the game was played
        data_tests:
          - not_null
      
      - name: season_segment
        description: Season segment (regular season, playoffs) in which the game was played
        data_tests:
          - not_null
      
      - name: min
        description: Minutes played by the player
      
      - name: fgm
        description: Field goals made by the player

      - name: fga
        description: Field goal attempts by the player

      - name: fg3m
        description: 3pt field goals made by the player

      - name: fg3a
        description: 3pt field goals attempts by the player

      - name: pts
        description: Total points scored by the player

      - name: plus_minus
        description: >
          Player plus-minus for the game, representing the team's point differential
          while the player was on the court.



